#!/bin/sh

output="{ \"value\": \"Many thanks Samir and Rob - it was great\" }"

echo >&2 'Super-complex enterprise server application initialising...'
echo >&2 'Still going...'
echo >&2 'Server initialised.'

while true; do
    echo -e "HTTP/1.1 200 OK\\r\\n\\r\\n$output" | nc -l -p 8080
done
